---
title: "Web Scraper - 04.3"
format: html
editor: visual
---

```{r}
pacman::p_load(rvest,xml2,dplyr, DBI, RMySQL, stringr, stringi, janitor, tidyr)
path <- getwd()
source(glue::glue(path,"/conn-db/connect-br-serie-a-db.R", sep=""))
source(glue::glue(path,"/webscraper/functions/extract_info_matches_players_2019-24.R", sep=""))
```

Conectando com o DB.

```{r}
con <- connect_br_serie_a_db()
```

```{r}
#dbGetQuery(con, "SHOW TABLES;")
#dbGetQuery(con, "SHOW COLUMNS FROM partidas_equipes;")
```

Criando um df para os IDs das equipes

```{r}
id_equipes <- dbGetQuery(con,
                         "SELECT ID_equipe, Equipe
                          FROM temporadas_times
                          WHERE ano BETWEEN 2019 AND 2024;"
                         )

id_equipes <- id_equipes |> distinct()
```

```{r}
# Lista de URLs a serem processadas
lista_urls <- dbGetQuery(con,
                         "SELECT links_completos
                          FROM partidas_equipes
                          WHERE YEAR(data) BETWEEN 2019 AND 2024;"
                         )
```

```{r}
# Convertendo para vetor de strings
lista_urls <- lista_urls$links_completos
```

```{r}
# Pré-aloca a lista de resultados com o mesmo tamanho da lista de URLs
resultados <- vector("list", length(lista_urls))

# Lista para armazenar links que deram erro
erros <- list()

# Loop sobre as URLs e coletando os dados
for (i in seq_along(lista_urls)) {
  Sys.sleep(5) # Pausa para evitar limite de requisições
  
  url <- lista_urls[i]
  
  # Usar tryCatch para capturar possíveis erros
  resultado <- tryCatch({
    # Executa a função processar_partida para a URL atual
    processar_partida(url, id_equipes)
    
  }, error = function(e) {
    # Em caso de erro, salva a URL que deu problema e a mensagem de erro
    message(paste("Erro ao processar o link:", url))
    message("Mensagem de erro:", e$message)
    
    # Armazena o link com erro e a mensagem de erro
    erros[[url]] <- e$message
    
    # Retorna NULL para manter a execução
    return(NULL)
  })
  
  # Armazena o resultado no índice correspondente
  resultados[[i]] <- resultado
}
```

```{r}
dbDisconnect(con)
```
