# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(parsnip)
    library(recipes)
    library(workflows)
    library(xgboost)
}
b <- board_folder(path = "/opt/ml/modelos")
v <- vetiver_pin_read(b, "br-serieA-xgb")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v, type = "prob")
}
